---
title: .small[Formation FRB-Cesab & GDR EcoStat]
subtitle: .ssmall[Bonnes pratiques pour une recherche reproductible en écologie numérique]
author: .verysmall[<br />Du 2 au 6 décembre 2019<br />Dans les locaux du Cesab à Montpellier]
output:
  xaringan::moon_reader:
    css: ["assets/css/xaringan-themer.css", "assets/css/custom.css"]
    lib_dir: "assets/libs"
    seal: true
    yolo: false
    self_contained: false
    nature:
      ratio: "4:3"
      titleSlideClass: ["right", "middle"]
      highlightStyle: 'zenburn'
      highlightLines: false
      countIncrementalSlides: false
      slideNumberFormat: "%current% / %total%"
      beforeInit: "assets/libs/macros.js"
---


## Programme

<br />

`r icon::fa("hand-point-right", color = "#3f3f3f")` &nbsp;[ .nolink[**Introduction à la recherche reproductible**]](sessions/session01/index.html)

`r icon::fa("hand-point-right", color = "#e1ddc0")` &nbsp;**Versioning du code et Travail collaboratif**

`r icon::fa("hand-point-right", color = "#3f3f3f")` &nbsp;[ .nolink[**API et Web scraping**]](sessions/session04/index01.html)

`r icon::fa("hand-point-right", color = "#3f3f3f")` &nbsp;[ .nolink[**Introduction au tidyverse**]](sessions/session04/index02.html)

`r icon::fa("hand-point-right", color = "#3f3f3f")` &nbsp;[ .nolink[**Données spatiales et cartographie**]](sessions/session05/index.html)

`r icon::fa("hand-point-right", color = "#e1ddc0")` &nbsp;**Research compendium et drake**

`r icon::fa("hand-point-right", color = "#3f3f3f")` &nbsp;[ .nolink[**Du script au package R**]](sessions/session07/index.html)

<br />

`r icon::fa("hand-point-right", color = "#49847b")` &nbsp;**Projets**
