---
title: Messages à retenir
subtitle: En guise d'au-revoir&nbsp;`r icon::fa("grin-tongue")`
author: <br /><br />L'équipe au complet<br />&nbsp;
date: .inst[Vendredi 6 novembre 2020]
output:
  xaringan::moon_reader:
    css: ["../../assets/css/xaringan-themer.css", "../../assets/css/custom.css"]
    lib_dir: "assets/libs"
    seal: true
    yolo: false
    self_contained: false
    nature:
      ratio: "4:3"
      titleSlideClass: ["right", "middle"]
      highlightStyle: 'zenburn'
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: ""
      beforeInit: "../../assets/libs/macros.js"
---

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

```{r eval=FALSE}
        >>> Article -> RECHERCHE NON REPRODUCTIBLE
        >>> Données + Métadonnées + Matériel & Méthodes + (Article) -> RECHERCHE REPRODUCTIBLE
```

---
**A vous de choisir le degré de complexité** mais respectez ces 3 principes :

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **Organisez vos fichiers selon les conventions de votre communauté**.

Organisez votre répertoire de travail avec des sous-dossiers : un `Research Compendium` - [Lecture](https://faculty.washington.edu/bmarwick/PDFs/Marwick-Boettiger-Mullen-2018-TAS-research-compendia.pdf)

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **Séparez données, méthodes et résultats**, tout en exposant leurs relations.

Développez des fonctions `r icon::fa("r-project")`
dans un sous-dossier `R/` et documentez-les avec `devtools::document()`

Intégrez vos analyses, résultats et éléments textuels avec `RMarkdown`

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **Specifiez l'environnement de développement** qui a été utilisé pour réaliser vos analyses.

Créez un fichier `DESCRIPTION` et utilisez les fonctions :
  - `devtools::install_deps()` : évite d'utiliser `install.packages()`
  - `devtools::load_all()` : évite d'utiliser `library()`

Créez un README pour décrire l'environnement de développement (e.g. `Session.info()`)

Et pour les plus audacieux, ayez l'esprit `docker` `r icon::fa("docker")`

---

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **pour un travail collaboratif **:

`Versionnez` votre développement avec `r icon::fa("git")` et GitHub/Lab `r icon::fa("github")` / `r `icon::fa("gitlab")`

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **Utilisez un "pipeline" si vos analyses prennent du temps **:

`{drake}` , `{targets}` 

`r icon::fa("hand-point-right", size = 1, color = "#3f3f3f")` **pour diffuser / réutiliser vos fonctions **:

Construisez un `package R` (n'oubliez pas le `.Rbuildignore`)



