---
title: "Solution spatial"
author: "N.S."
date: "3 November 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
```

## Load libraries

```{r}
library(sf)
library(readr)
library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
```

## Part 1

### Load data
```{r}
wf_eco <- read_csv(here::here("data","wildfinder-ecoregions_list.csv"))
wf_ecosp <- read_csv(here::here("data","wildfinder-ecoregions_species.csv"))
wf_sp <- read_csv(here::here("data","wildfinder-mammals_list.csv"))
wwf <- st_read(here::here("data","wwf_terr_ecos.shp"))

# world object
world <- ne_countries(scale = "medium", returnclass = "sf")

```

### Data wrangling
```{r cars}
ursus1 <- wf_sp %>%
  # filter the species
  filter(sci_name == "Ursus arctos") %>%
  # join with wildfinder species and ecoregions
  left_join(wf_ecosp) %>%
  # join with ecoregion info
  left_join(wf_eco) 

wwf_ursus1 <- wwf %>%
  # rename code of ecoregion that has different name in wildfinder and wwf ecoregions
  rename(ecoregion_id = eco_code) %>%
  inner_join(ursus1)
```

### Figure 1


```{r pressure, echo=FALSE}
ggplot(world) +
  geom_sf(size = 0.1) +
  geom_sf(fill = "darkblue", color = "darkblue", data = wwf_ursus1) +
  theme_minimal() +
  xlab("Longitude") + ylab("Latitude") 
```


## Part 2

### Wrangle  

```{r}
ursus2 <- wf_sp %>%
  filter(sci_name == "Ursus americanus") %>%
  left_join(wf_ecosp) %>%
  left_join(wf_eco)

wwf_ursus2 <- wwf %>%
  rename(ecoregion_id = eco_code) %>%
  inner_join(ursus2)

# use sf to get the intersection of the habitat of two species 
wwf_ursus_overlap <- 
  st_intersection(wwf_ursus1, wwf_ursus2)
```


### Figure 2 

```{r}
ggplot(world) +
  geom_sf(size = 0.1) +
  geom_sf(fill = "grey", color = "grey", 
          data = wwf_ursus1, size = 0.1) +
  geom_sf(fill = "black", color = "black", 
          data = wwf_ursus_overlap, size = 0.1) +
  theme_minimal() +
  xlab("Longitude") + ylab("Latitude") 
```

## Part 3 

```{r}
# transform projection
world2 <- st_transform(world, st_crs("+init=epsg:2163"))

 ggplot(world2) +
   geom_sf(size = 0.1) +
   geom_sf(fill = "grey", color = "grey", 
           data = wwf_ursus1) +
   geom_sf(fill = "black", color = "black",
           data = wwf_ursus_overlap) +
   theme_minimal()

```







