---
title: Exercice n°5
subtitle: <i>Faire une recette de pizza collaborative avec git </i><br /><br /><br /><br />
output:
  xaringan::moon_reader:
    css: ["../../assets/css/xaringan-themer.css", "../../assets/css/custom.css"]
    lib_dir: "assets/libs"
    seal: true
    yolo: false
    self_contained: false
    nature:
      ratio: "4:3"
      titleSlideClass: ["right", "middle"]
      highlightStyle: 'zenburn'
      highlightLines: false
      countIncrementalSlides: false
      slideNumberFormat: "%current% / %total%"
      beforeInit: "../../assets/libs/macros.js"
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'assets/chunks/', cache.path = "assets/cache/")
```



## Instructions

Mettez vous par groupe de 4 personnes. Chacun se crée un nouveau dépôt sur GitHub. Dans ce dépôt, ajoutez un fichier `.txt` qui contient votre recette de pizza. Le suivre, faire des changements, etc.

Sur GitHub, ajoutez une personne de votre groupe comme collaborateur de votre projet (les recettes à deux c'est mieux)

Horreur, vous vous rendez compte que les autres membres de votre groupe ont oublié des ingrédients importants dans leur recette : les olives noires, les anchois marinés et le gorgonzola. Mettez en oeuvre 3 solutions pour interagir et leur faire remarquer que leur recette peut être améliorée. En fonction de votre statut dans le projet et votre souhait de vous impliquer :

- utilisez les issues pour dire au développeur que sa recette peut être améliorée
- si vous êtes collaborateur, cloner le dépôt, faire les modifications et les envoyer
- si vous ne l'êtes pas, forkez, clonez, et essayez la pull request
    
---

## Ressources

    https://guides.github.com/features/issues/
    https://guides.github.com/activities/forking/
    https://jarv.is/notes/how-to-pull-request-fork-github/

